version: '3'

services:
  api-gateway:
    restart: always
    ports:
      - 3000:3000
    image: ghcr.io/gear-tech/gear-js-api-gateway:qa
    environment:
      KAFKA_GROUP_ID: ${KAFKA_GROUP_ID}
      KAFKA_CLIENT_ID: ${KAFKA_CLIENT_ID}
      KAFKA_BROKERS: ${KAFKA_BROKERS}
      KAFKA_SASL_USERNAME: ${KAFKA_SASL_USERNAME}
      KAFKA_SASL_PASSWORD: ${KAFKA_SASL_PASSWORD}
      CAPTCH_SECRET: 0xfF8C6A74C8EcD1Db7A7A5772F815255f4B661197
      PORT: 3000
