---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: dashy-conf
  namespace: monitoring
  labels:
    app: dashy
data:
  conf.yml: |
    appConfig:
      theme: colorful
      layout: auto
      iconSize: large
      language: en
      startingView: default
      defaultOpeningMethod: newtab
      statusCheck: true
      statusCheckInterval: 10
      faviconApi: google
      routingMode: history
      enableMultiTasking: false
      widgetsAlwaysUseProxy: false
      webSearch:
        disableWebSearch: true
        searchEngine: ''
        openingMethod: newtab
        searchBangs: {}
      enableFontAwesome: true
      hideComponents:
        hideHeading: false
        hideNav: true
        hideSearch: true
        hideSettings: true
        hideFooter: true
      auth:
        enableGuestAccess: false
        users:
        - user: gear-admin
          hash: 73234e23a0a3ab5082471798285db0f00ed57ad5b617734c89b5d6d13facc791
          type: admin
        enableKeycloak: false
      showSplashScreen: false
      preventWriteToDisk: true
      preventLocalSave: true
      disableConfiguration: true
      allowConfigEdit: false
      enableServiceWorker: true
      disableContextMenu: true
      disableUpdateChecks: true
      disableSmartSort: true
      enableErrorReporting: false
    pageInfo:
      title: Gear Technologies
      description: infrastructure
      navLinks:
        - title: ':)'
          path: /
          footerText: ''
    sections:
      - name: Main
        icon: ''
        displayData:
          sortBy: default
          rows: 1
          cols: 1
          collapsed: false
          hideForGuests: false
        items:
          - title: Gear-tech.io
            icon: favicon
            url: https://www.gear-tech.io/
            target: newtab
            statusCheckAllowInsecure: true
            id: 0_389_geartechio
          - title: Telemetry
            icon: favicon
            url: https://telemetry.gear-tech.io
            target: newtab
            statusCheckAllowInsecure: true
            id: 0_389_telemetry
          - title: GitHub
            icon: favicon
            url: https://github.com/gear-tech
            target: newtab
            statusCheckAllowInsecure: true
            id: 1_389_github
      - name: ENV
        displayData:
          sortBy: default
          rows: 1
          cols: 1
          collapsed: false
          hideForGuests: false
        items:
          - title: Stage
            icon: favicon
            url: https://staging-env.gear-tech.io/
            target: newtab
            statusCheckAllowInsecure: true
            id: 3_1505_stage
          - title: Test
            icon: favicon
            url: https://test-env.gear-tech.io/
            target: newtab
            statusCheckAllowInsecure: true
            id: 3_1505_test
      - name: Monitoring
        displayData:
          sortBy: default
          rows: 1
          cols: 1
          collapsed: false
          hideForGuests: false
        items:
          - title: Grafana
            icon: https://monitoring.gear-tech.io/grafana/public/img/grafana_icon.svg
            url: https://monitoring.gear-tech.io/grafana
            target: newtab
            statusCheckAllowInsecure: true
            id: 0_1062_grafana
          - title: Prometheus
            icon: https://prometheus.io/assets/favicons/favicon.ico
            url: https://monitoring.gear-tech.io/prometheus/targets
            target: newtab
            statusCheckAllowInsecure: true
            statusCheckAcceptCodes: "401"
            id: 1_1062_prometheus
      - name: Infrastructure
        displayData:
          sortBy: default
          rows: 1
          cols: 1
          collapsed: false
          hideForGuests: false
        items:
          - title: AWS
            icon: favicon
            url: https://console.aws.amazon.com/console/
            target: newtab
            statusCheckAllowInsecure: true
            id: 0_1505_aws
          - title: k8s
            icon: https://kubernetes.io/images/favicon.png
            url: https://kubernetes-ui.gear-tech.io
            target: newtab
            statusCheckAllowInsecure: true
            statusCheckAcceptCodes: "401"
            id: 1_1505_ks

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dashy
  namespace: monitoring
  labels:
    app: dashy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dashy
  template:
    metadata:
      labels:
        app: dashy
    spec:
      containers:
      - name: dashy
        image: lissy93/dashy:latest
        ports:
          - containerPort: 80
        volumeMounts:
        - name: dashy-conf
          mountPath: /app/public/conf.yml
          subPath: conf.yml
        env:
          - name: NODE_ENV
            value: 'production'
      volumes:
        - name: dashy-conf
          configMap:
            name: dashy-conf

---
apiVersion: v1
kind: Service
metadata:
  name: dashy
  namespace: monitoring
  labels:
    app: dashy
spec:
  selector:
    app: dashy
  ports:
  - name: dashy
    protocol: TCP
    port: 80

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dashy-ingress
  namespace: monitoring
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: 'true'
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - monitoring.gear-tech.io
      secretName: tlscert-with-ca
  rules:
    - host: monitoring.gear-tech.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: dashy
                port:
                  number: 80
