name: AWS-EKS-backup

on:
  workflow_dispatch:
    inputs:
      custom_backup_name:
        description: "NOT REQUIRED. Custom name backup. Use separator - :"   
        required: false
      namespaces:
        description: "List namespaces. Use separator , :"   
        required: true
      source_cluster:
        description: 'Select source cluster:'
        required: true
        type: choice
        options:
          - stg
          - prod

concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}

env:
  BACKUP_NAME_FULL: ${{ github.run_number }}-${{ github.event.inputs.source_cluster }}---full-backup-`date +"%d-%m-%Y"`
  BACKUP_NAME_SPECIFIC: ${{ github.run_number }}-${{ github.event.inputs.source_cluster }}---specific-backup-`date +"%d-%m-%Y"`
    
jobs:
  backup_all_namsepaces:
    name: "Backup all namespaces on ${{ github.event.inputs.source_cluster }}"
    if: ${{ github.event.inputs.namespaces == 'All' }}
    runs-on: ubuntu-latest
    steps:
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.VELERO_ID_PROD }}
          aws-secret-access-key: ${{ secrets.VELERO_KEY_PROD }}
          aws-region: ${{ secrets.VELERO_REGION_PROD }}

      - run: |
          aws eks --region ${{ secrets.VELERO_REGION_PROD }} update-kubeconfig --kubeconfig $HOME/.kube/config_prod --name k8s-gear

      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.VELERO_ID_STG }}
          aws-secret-access-key: ${{ secrets.VELERO_KEY_STG }}
          aws-region: ${{ secrets.VELERO_REGION_STG }}

      - run: |
          aws eks --region ${{ secrets.VELERO_REGION_STG }} update-kubeconfig --kubeconfig $HOME/.kube/config_stg --name k8s-gear-stg

      - run: |
          wget https://github.com/vmware-tanzu/velero/releases/download/v1.8.1/velero-v1.8.1-linux-amd64.tar.gz
          tar -xvf velero*.tar.gz
          cd ./velero-v1.8.1-linux-amd64
          chmod +x ./velero

      - run: |
          ./velero backup create \
          ${{ github.event.inputs.custom_backup_name || env.BACKUP_NAME_FULL }} \
          --kubeconfig $HOME/.kube/config_prod \
          --wait
        working-directory: ./velero-v1.8.1-linux-amd64
        if: ${{ github.event.inputs.source_cluster == 'prod' }}

      - run: |
          ./velero backup create \
          ${{ github.event.inputs.custom_backup_name || env.BACKUP_NAME_FULL }} \
          --kubeconfig $HOME/.kube/config_stg \
          --wait
        working-directory: ./velero-v1.8.1-linux-amd64
        if: ${{ github.event.inputs.source_cluster == 'stg' }}

      - run: |
          ./velero backup describe  ${{ github.event.inputs.custom_backup_name || env.BACKUP_NAME_FULL }} --kubeconfig $HOME/.kube/config_prod
        working-directory: ./velero-v1.8.1-linux-amd64
        if: ${{ github.event.inputs.source_cluster == 'prod' }}

      - run: |
          ./velero backup describe  ${{ github.event.inputs.custom_backup_name || env.BACKUP_NAME_FULL }} --kubeconfig $HOME/.kube/config_stg
        working-directory: ./velero-v1.8.1-linux-amd64
        if: ${{ github.event.inputs.source_cluster == 'stg' }}

      - run: |
          ./velero backup logs  ${{ github.event.inputs.custom_backup_name || env.BACKUP_NAME_FULL }} --kubeconfig $HOME/.kube/config_prod
        working-directory: ./velero-v1.8.1-linux-amd64
        if: ${{ github.event.inputs.source_cluster == 'prod' }}

      - run: |
          ./velero backup logs  ${{ github.event.inputs.custom_backup_name || env.BACKUP_NAME_FULL }} --kubeconfig $HOME/.kube/config_stg
        working-directory: ./velero-v1.8.1-linux-amd64
        if: ${{ github.event.inputs.source_cluster == 'stg' }}


  backup_specific_namsepace:
    name: "Backup namespaces: ${{ github.event.inputs.namespaces }} on ${{ github.event.inputs.source_cluster }}"
    if: ${{ github.event.inputs.namespaces != 'All' }}
    runs-on: ubuntu-latest
    steps:
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.VELERO_ID_PROD }}
          aws-secret-access-key: ${{ secrets.VELERO_KEY_PROD }}
          aws-region: ${{ secrets.VELERO_REGION_PROD }}

      - run: |
          aws eks --region ${{ secrets.VELERO_REGION_PROD }} update-kubeconfig --kubeconfig $HOME/.kube/config_prod --name k8s-gear

      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.VELERO_ID_STG }}
          aws-secret-access-key: ${{ secrets.VELERO_KEY_STG }}
          aws-region: ${{ secrets.VELERO_REGION_STG }}

      - run: |
          aws eks --region ${{ secrets.VELERO_REGION_STG }} update-kubeconfig --kubeconfig $HOME/.kube/config_stg --name k8s-gear-stg

      - run: |
          wget https://github.com/vmware-tanzu/velero/releases/download/v1.8.1/velero-v1.8.1-linux-amd64.tar.gz
          tar -xvf velero*.tar.gz
          cd ./velero-v1.8.1-linux-amd64
          chmod +x ./velero

      - run: |
          ./velero backup create \
          ${{ github.event.inputs.custom_backup_name || env.BACKUP_NAME_FULL }} \
          --include-namespaces ${{ github.event.inputs.namespaces }} \
          --kubeconfig $HOME/.kube/config_prod \
          --wait
        working-directory: ./velero-v1.8.1-linux-amd64
        if: ${{ github.event.inputs.source_cluster == 'prod' }}

      - run: |
          ./velero backup create \
          ${{ github.event.inputs.custom_backup_name || env.BACKUP_NAME_FULL }} \
          --include-namespaces ${{ github.event.inputs.namespaces }} \
          --kubeconfig $HOME/.kube/config_stg \
          --wait
        working-directory: ./velero-v1.8.1-linux-amd64
        if: ${{ github.event.inputs.source_cluster == 'stg' }}

      - run: |
          ./velero backup describe  ${{ github.event.inputs.custom_backup_name || env.BACKUP_NAME_SPECIFIC }} --kubeconfig $HOME/.kube/config_prod
        working-directory: ./velero-v1.8.1-linux-amd64
        if: ${{ github.event.inputs.source_cluster == 'prod' }}

      - run: |
          ./velero backup describe  ${{ github.event.inputs.custom_backup_name || env.BACKUP_NAME_SPECIFIC }} --kubeconfig $HOME/.kube/config_stg
        working-directory: ./velero-v1.8.1-linux-amd64
        if: ${{ github.event.inputs.source_cluster == 'stg' }}

      - run: |
          ./velero backup logs  ${{ github.event.inputs.custom_backup_name || env.BACKUP_NAME_SPECIFIC }} --kubeconfig $HOME/.kube/config_prod
        working-directory: ./velero-v1.8.1-linux-amd64
        if: ${{ github.event.inputs.source_cluster == 'prod' }}

      - run: |
          ./velero backup logs  ${{ github.event.inputs.custom_backup_name || env.BACKUP_NAME_SPECIFIC }} --kubeconfig $HOME/.kube/config_stg
        working-directory: ./velero-v1.8.1-linux-amd64
        if: ${{ github.event.inputs.source_cluster == 'stg' }}
