name: e2e tests

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches: master
    paths: 
      - website/**
  workflow_dispatch:

env:
  DOCKER_REGISTRY: ghcr.io
  DOCKER_USER: ${{ github.actor }}
  DOCKER_PASSWORD: ${{ github.token }}
  DOCKER_REPOSITORY: ${{ github.repository_owner }}
  DOCKER_IMAGE_TAG: latest
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: ${{ secrets.AWS_REGION }}
  KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
  KUBE_NAMESPACE: test-env

jobs:
  unit-tests:
    name: Unit tests 'data-storage'
    runs-on: k8s-runner
    steps:
      - name: Fix permissions
        run: |
          sudo chown -R runner:runner /runner/_work

      - name: Cancel previous
        uses: styfle/cancel-workflow-action@HEAD
        with:
          access_token: ${{ github.token }}

      - name: Checkout
        uses: actions/checkout@HEAD

      - name: Yarn install & configure
        run: |
          sudo yarn set version berry
          sudo yarn config set nodeLinker node-modules
          sudo yarn config set enableGlobalCache true
          sudo yarn config set globalFolder /mnt/cashes/yarn
          sudo yarn plugin import @yarnpkg/plugin-workspace-tools
          sudo yarn install

      - name: Build 'interfaces' & 'jsonrpc-errors'
        run: sudo yarn build:interfaces && yarn build:jsonrpc-errors
        working-directory: website/

      - name: Unit tests
        run: sudo yarn test
        working-directory: website/data-storage/

  wait-previous-run:
    name: Wait previous run
    needs: unit-tests
    runs-on: k8s-runner
    steps:
      - name: Wait previous run
        uses: mktcode/consecutive-workflow-action@HEAD
        with:
          token: ${{ github.token }}

  build-and-push-gear-node-image:
    name: Build & push 'gear-node'
    needs: wait-previous-run
    runs-on: k8s-runner
    steps:
      - name: Fix permissions
        run: |
          sudo chown -R runner:runner /runner/_work

      - name: Checkout
        uses: actions/checkout@HEAD

      - name: Docker login
        run: |
          echo ${{ env.DOCKER_PASSWORD }} \
          | docker login ${{ env.DOCKER_REGISTRY }} \
          -u ${{ env.DOCKER_USER }} \
          --password-stdin

      - name: Build image
        run: |
          docker build \
          -t ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_REPOSITORY }}/gear-node:dev \
          -f k8s/gear-node/Dockerfile .

      - name: Push image
        run: |
          docker push \
          ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_REPOSITORY }}/gear-node:dev

      - name: Docker logout
        run: |
          docker logout
